# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170421_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(verbose_name='Published'),
        ),
    ]
