# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170421_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='published',
        ),
    ]
